### PR TITLE
Fixes a lot of formatting and code convention issues

### PR DESCRIPTION
**Pull request by rowleya**

### CODE REVIEW

**Comment by alan-stokes** [comment]
please fix conflicts, as every line in the conflicts are different.

**Comment by rowleya** [comment]
Ready to go now...

**Comment by dkfellows** [comment]
Why did you change tabs to spaces? This is Java, not Python. Also, the code now massively overuses `final`.

This is a terrible change.

**Comment by rowleya** [comment]
Spaces work better than tabs in general as then the look of the code doesn't depend on your tab setting.  Note that the original Java coding conventions (from 1999) say that you should use 4 spaces as an indent.  It then goes on to say that you can use spaces or tabs, but that the tab setting should be 8 spaces; this says "use spaces" to me, as otherwise you will have to mix...

Using final as much as possible is generally a good thing in Java if you don't intend changing the variables by accident.  I am not particularly bothered however on this point.  In general, final for method parameters is a good idea unless they are meant to be changed by the method.

**Pull request merged**
